server:
  port: 8000

spring:
  application:
    name: order-consumer-8000

eureka:
  client:
    fetch-registry: true # 这个不开启会导致不去注册中心拉取服务, 导致找不到服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#开启支持hystrix
feign:
  hystrix:
    enabled: true